# Generated by Django 4.0.3 on 2022-04-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pokemonfood_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonfood',
            name='quantity',
        ),
    ]
